# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/llf/faNotify

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/llf/faNotify

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/llf/faNotify/CMakeFiles /home/llf/faNotify//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/llf/faNotify/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named LazyFetcher

# Build rule for target.
LazyFetcher: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 LazyFetcher
.PHONY : LazyFetcher

# fast build rule for target.
LazyFetcher/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LazyFetcher.dir/build.make CMakeFiles/LazyFetcher.dir/build
.PHONY : LazyFetcher/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LazyFetcher.dir/build.make CMakeFiles/LazyFetcher.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LazyFetcher.dir/build.make CMakeFiles/LazyFetcher.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LazyFetcher.dir/build.make CMakeFiles/LazyFetcher.dir/main.cpp.s
.PHONY : main.cpp.s

src/addMarks.o: src/addMarks.cpp.o
.PHONY : src/addMarks.o

# target to build an object file
src/addMarks.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LazyFetcher.dir/build.make CMakeFiles/LazyFetcher.dir/src/addMarks.cpp.o
.PHONY : src/addMarks.cpp.o

src/addMarks.i: src/addMarks.cpp.i
.PHONY : src/addMarks.i

# target to preprocess a source file
src/addMarks.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LazyFetcher.dir/build.make CMakeFiles/LazyFetcher.dir/src/addMarks.cpp.i
.PHONY : src/addMarks.cpp.i

src/addMarks.s: src/addMarks.cpp.s
.PHONY : src/addMarks.s

# target to generate assembly for a file
src/addMarks.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LazyFetcher.dir/build.make CMakeFiles/LazyFetcher.dir/src/addMarks.cpp.s
.PHONY : src/addMarks.cpp.s

src/blobState.o: src/blobState.cpp.o
.PHONY : src/blobState.o

# target to build an object file
src/blobState.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LazyFetcher.dir/build.make CMakeFiles/LazyFetcher.dir/src/blobState.cpp.o
.PHONY : src/blobState.cpp.o

src/blobState.i: src/blobState.cpp.i
.PHONY : src/blobState.i

# target to preprocess a source file
src/blobState.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LazyFetcher.dir/build.make CMakeFiles/LazyFetcher.dir/src/blobState.cpp.i
.PHONY : src/blobState.cpp.i

src/blobState.s: src/blobState.cpp.s
.PHONY : src/blobState.s

# target to generate assembly for a file
src/blobState.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LazyFetcher.dir/build.make CMakeFiles/LazyFetcher.dir/src/blobState.cpp.s
.PHONY : src/blobState.cpp.s

src/containerClass.o: src/containerClass.cpp.o
.PHONY : src/containerClass.o

# target to build an object file
src/containerClass.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LazyFetcher.dir/build.make CMakeFiles/LazyFetcher.dir/src/containerClass.cpp.o
.PHONY : src/containerClass.cpp.o

src/containerClass.i: src/containerClass.cpp.i
.PHONY : src/containerClass.i

# target to preprocess a source file
src/containerClass.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LazyFetcher.dir/build.make CMakeFiles/LazyFetcher.dir/src/containerClass.cpp.i
.PHONY : src/containerClass.cpp.i

src/containerClass.s: src/containerClass.cpp.s
.PHONY : src/containerClass.s

# target to generate assembly for a file
src/containerClass.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LazyFetcher.dir/build.make CMakeFiles/LazyFetcher.dir/src/containerClass.cpp.s
.PHONY : src/containerClass.cpp.s

src/databaseSingleton.o: src/databaseSingleton.cpp.o
.PHONY : src/databaseSingleton.o

# target to build an object file
src/databaseSingleton.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LazyFetcher.dir/build.make CMakeFiles/LazyFetcher.dir/src/databaseSingleton.cpp.o
.PHONY : src/databaseSingleton.cpp.o

src/databaseSingleton.i: src/databaseSingleton.cpp.i
.PHONY : src/databaseSingleton.i

# target to preprocess a source file
src/databaseSingleton.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LazyFetcher.dir/build.make CMakeFiles/LazyFetcher.dir/src/databaseSingleton.cpp.i
.PHONY : src/databaseSingleton.cpp.i

src/databaseSingleton.s: src/databaseSingleton.cpp.s
.PHONY : src/databaseSingleton.s

# target to generate assembly for a file
src/databaseSingleton.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LazyFetcher.dir/build.make CMakeFiles/LazyFetcher.dir/src/databaseSingleton.cpp.s
.PHONY : src/databaseSingleton.cpp.s

src/sparseAllocator.o: src/sparseAllocator.cpp.o
.PHONY : src/sparseAllocator.o

# target to build an object file
src/sparseAllocator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LazyFetcher.dir/build.make CMakeFiles/LazyFetcher.dir/src/sparseAllocator.cpp.o
.PHONY : src/sparseAllocator.cpp.o

src/sparseAllocator.i: src/sparseAllocator.cpp.i
.PHONY : src/sparseAllocator.i

# target to preprocess a source file
src/sparseAllocator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LazyFetcher.dir/build.make CMakeFiles/LazyFetcher.dir/src/sparseAllocator.cpp.i
.PHONY : src/sparseAllocator.cpp.i

src/sparseAllocator.s: src/sparseAllocator.cpp.s
.PHONY : src/sparseAllocator.s

# target to generate assembly for a file
src/sparseAllocator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LazyFetcher.dir/build.make CMakeFiles/LazyFetcher.dir/src/sparseAllocator.cpp.s
.PHONY : src/sparseAllocator.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... LazyFetcher"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/addMarks.o"
	@echo "... src/addMarks.i"
	@echo "... src/addMarks.s"
	@echo "... src/blobState.o"
	@echo "... src/blobState.i"
	@echo "... src/blobState.s"
	@echo "... src/containerClass.o"
	@echo "... src/containerClass.i"
	@echo "... src/containerClass.s"
	@echo "... src/databaseSingleton.o"
	@echo "... src/databaseSingleton.i"
	@echo "... src/databaseSingleton.s"
	@echo "... src/sparseAllocator.o"
	@echo "... src/sparseAllocator.i"
	@echo "... src/sparseAllocator.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

